name: Override Bot
on:
  issue_comment:
    types: [created]
jobs:
  rebase:
    name: Build Manifests and Rebase
    if: (github.event.issue.pull_request != '') && (contains(github.event.comment.body, '/override-bot'))
    runs-on: ubuntu-latest
    steps:
      - name: Find Lanes for Override across open PRs
        run: python ./automation/override-bot/override-bot.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}