name: Override Bot
on:
  issue_comment:
    types: [created]
jobs:
  override:
    name: Check for redundant CI lanes for override
    if: (github.event.issue.pull_request != '') && (contains(github.event.comment.body, '/override-bot'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Find Lanes for Override across open PRs
        run: python ./automation/override-bot/override-bot.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}