name: Auto-Bump Components Versions
on: push

jobs:
  build:
    name: bump bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create local changes
        run: |
          pwd
          $(pwd)/automation/release-bumber/release-bumper.sh