name: Auto-Bump Components Versions
on: push

jobs:
  build:
    name: bump bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release_bumper
      - name: Check for new releases and update
        run: |
          ./automation/release-bumper/release-bumper.sh
      - name: Set variables and remove temporary files
      - run: echo "::set-env name=UPDATED_COMPONENT::$(cat updated_component.txt)";
      - run: echo "::set-env name=UPDATED_VERSION::$(cat updated_version.txt)";
      - run: rm -f updated_component.txt updated_version.txt
      - uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump $UPDATED_COMPONENT to $UPDATED_VERSION"
          committer: GitHub <noreply@github.com>
          title: "Bump $UPDATED_COMPONENT to $UPDATED_VERSION"
          body: |
            Bump $UPDATED_COMPONENT to $UPDATED_VERSION
            Excecuted by HCO Release-Bumper Bot.
          assignees: orenc1
          reviewers: orenc1
          team-reviewers: owners, maintainers
          draft: false
          branch: bdika