name: Auto-Bump Components Versions
on: push

jobs:
  build:
    name: bump bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release_bumper
      - name: Create local changes
        run: |
          ./automation/release-bumber/release-bumper.sh