name: Auto-Bump Components Versions
on: push

jobs:
  build:
    name: bump bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: release_bumper
      - name: Check for new releases and update
        run: |
          ./automation/release-bumper/release-bumper.sh
      - uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: bump versions
          committer: GitHub <noreply@github.com>
          title: '[test] bump versions'
          body: |
            Hello
            - This is a test
          assignees: orenc1
          reviewers: orenc1
          team-reviewers: owners, maintainers
          draft: false
          branch: bdika