name: Auto-Bump Components Versions
on:
  schedule:
    - cron:  '51 16 * * *'

jobs:
  build:
    name: bump bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create local changes
        run: ./automation/release-bumber/release-bumper.sh